"""Parses CVM's "Negociação de Valores Mobiliários pela própria companhia,
suas controladas e coligadas" filing (a PDF -- CVM's own open data only
structures the insider-disclosure half of this form, not this one).

The PDF is auto-generated by CVM's ENET system from the same web form for
every filer, so its table layout is consistent: a "Saldo Inicial" position
block, a "Movimentações no Mês" table (one row per trade), and a "Saldo
Final" block, repeated once per reporting entity (the company itself, and
any controladas/coligadas that also traded).
"""
import io
import re

import pdfplumber

SHARE_ASSETS = {"Ações", "Units", "BDR Patrocinados"}
TRADE_RE = re.compile(r"(Compra|Venda)")


def _clean(cell):
    return (cell or "").replace("\n", " ").strip()


def _br_num(s):
    s = _clean(s)
    if not s:
        return None
    try:
        return float(s.replace(".", "").replace(",", "."))
    except ValueError:
        return None


def parse_buyback_pdf(pdf_bytes: bytes, month: str) -> list[dict]:
    """Returns trade records shaped like the insider records elsewhere in
    this pipeline (asset/movement/is_trade/qty/price/volume/ref), so the
    same monthly-aggregation and charting code can consume both."""
    records = []
    with pdfplumber.open(io.BytesIO(pdf_bytes)) as pdf:
        for page in pdf.pages:
            for table in page.extract_tables():
                for row in table:
                    asset = _clean(row[0])
                    if asset not in SHARE_ASSETS:
                        continue
                    m = TRADE_RE.search(" ".join(_clean(c) for c in row if c is not None))
                    if not m:
                        continue
                    nums = [_br_num(c) for c in row if _br_num(c) is not None]
                    if len(nums) < 3:
                        continue
                    qty, price, volume = nums[-3], nums[-2], nums[-1]
                    records.append({
                        "ref": month,
                        "asset": asset,
                        "movement": f"{m.group(1)} à vista",
                        "is_trade": True,
                        "qty": qty,
                        "price": price,
                        "volume": volume,
                    })
    return records
